/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminAdminsRouteImport } from './routes/_admin/admins'
import { Route as AdminAuditRouteImport } from './routes/_admin/audit'
import { Route as AdminCategoriesRouteImport } from './routes/_admin/categories'
import { Route as AdminConversationsRouteImport } from './routes/_admin/conversations'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminMediaRouteImport } from './routes/_admin/media'
import { Route as AdminPagesRouteImport } from './routes/_admin/pages'
import { Route as AdminProductsRouteImport } from './routes/_admin/products'
import { Route as AdminReviewsRouteImport } from './routes/_admin/reviews'
import { Route as AdminSellersRouteImport } from './routes/_admin/sellers'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins': typeof AdminAdminsRoute
  '/audit': typeof AdminAuditRoute
  '/categories': typeof AdminCategoriesRoute
  '/conversations': typeof AdminConversationsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/media': typeof AdminMediaRoute
  '/pages': typeof AdminPagesRoute
  '/products': typeof AdminProductsRoute
  '/reviews': typeof AdminReviewsRoute
  '/sellers': typeof AdminSellersRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins': typeof AdminAdminsRoute
  '/audit': typeof AdminAuditRoute
  '/categories': typeof AdminCategoriesRoute
  '/conversations': typeof AdminConversationsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/media': typeof AdminMediaRoute
  '/pages': typeof AdminPagesRoute
  '/products': typeof AdminProductsRoute
  '/reviews': typeof AdminReviewsRoute
  '/sellers': typeof AdminSellersRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/admins': typeof AdminAdminsRoute
  '/_admin/audit': typeof AdminAuditRoute
  '/_admin/categories': typeof AdminCategoriesRoute
  '/_admin/conversations': typeof AdminConversationsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/media': typeof AdminMediaRoute
  '/_admin/pages': typeof AdminPagesRoute
  '/_admin/products': typeof AdminProductsRoute
  '/_admin/reviews': typeof AdminReviewsRoute
  '/_admin/sellers': typeof AdminSellersRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/users': typeof AdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins'
    | '/audit'
    | '/categories'
    | '/conversations'
    | '/dashboard'
    | '/media'
    | '/pages'
    | '/products'
    | '/reviews'
    | '/sellers'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins'
    | '/audit'
    | '/categories'
    | '/conversations'
    | '/dashboard'
    | '/media'
    | '/pages'
    | '/products'
    | '/reviews'
    | '/sellers'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/admins'
    | '/_admin/audit'
    | '/_admin/categories'
    | '/_admin/conversations'
    | '/_admin/dashboard'
    | '/_admin/media'
    | '/_admin/pages'
    | '/_admin/products'
    | '/_admin/reviews'
    | '/_admin/sellers'
    | '/_admin/settings'
    | '/_admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admins': {
      id: '/_admin/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit': {
      id: '/_admin/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/categories': {
      id: '/_admin/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/conversations': {
      id: '/_admin/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/media': {
      id: '/_admin/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pages': {
      id: '/_admin/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reviews': {
      id: '/_admin/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sellers': {
      id: '/_admin/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
