/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardAdminsRouteImport } from './routes/dashboard.admins'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardDataEntityRouteImport } from './routes/dashboard.data.$entity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminsRoute = DashboardAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDataEntityRoute = DashboardDataEntityRouteImport.update({
  id: '/data/$entity',
  path: '/data/$entity',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/data/$entity': typeof DashboardDataEntityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/data/$entity': typeof DashboardDataEntityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admins': typeof DashboardAdminsRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/data/$entity': typeof DashboardDataEntityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/admins'
    | '/dashboard/security'
    | '/dashboard/'
    | '/dashboard/data/$entity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/account'
    | '/dashboard/admins'
    | '/dashboard/security'
    | '/dashboard'
    | '/dashboard/data/$entity'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/account'
    | '/dashboard/admins'
    | '/dashboard/security'
    | '/dashboard/'
    | '/dashboard/data/$entity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admins': {
      id: '/dashboard/admins'
      path: '/admins'
      fullPath: '/dashboard/admins'
      preLoaderRoute: typeof DashboardAdminsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data/$entity': {
      id: '/dashboard/data/$entity'
      path: '/data/$entity'
      fullPath: '/dashboard/data/$entity'
      preLoaderRoute: typeof DashboardDataEntityRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminsRoute: typeof DashboardAdminsRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDataEntityRoute: typeof DashboardDataEntityRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminsRoute: DashboardAdminsRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDataEntityRoute: DashboardDataEntityRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
